--- 
dynamic: 
  client.dll:
    - 
      commands: 
        offset: 1
      name: DotaInput
      signature: "A1 ? ? ? ? B9 ? ? ? ? FF 90 98 00 00 00"
    - 
      commands: 
        offset: 4
      name: PlayerResource
      signature: "74 4D 8B 35 ? ? ? ? 85 F6 74 67"
    - 
      commands: 
        offset: 4
      name: GameRules
      signature: "74 4B 8B 0D ? ? ? ? 85 C9 74 06"
    - 
      commands: 
        offset: 3
      name: Hud
      signature: "7C E9 B9 ? ? ? ? E8 ? ? ? ?"
    - 
      commands: 
        offset: 3
      name: ClientMode
      signature: "74 11 68 ? ? ? ? FF 15 ? ? ? ? 83 C4 04 5E 5D C3 8B 0D ? ? ? ? 8B B6 0C 04 00 00"
    - 
      commands: 
        offset: 1
      name: ModifierDefaultParams
      signature: "68 ? ? ? ? 6A 17 8B C8"
    - 
      commands: 
        offset: 2
      name: GameSystemsRetriever
      signature: "8B 15 ? ? ? ? 85 C0 7E 0E"

  engine.dll: 
    - 
      commands: 
        offset: 4
      name: CommandBuffer
      signature: "EB 5E FF 05 ? ? ? ?"
static: 
  client.dll:
    - 
      commands: 
        relative: 0
      name: "GameRules::GetAnnouncer"
      signature: "E8 ? ? ? ? 8B 0D ? ? ? ? 8B D8 83 79 30 00"
    - 
      commands: 
        relative: 0
      name: "GameRules::GetKillingSpreeAnnouncer"
      signature: "E8 ? ? ? ? 8B F0 85 F6 0F 84 ? ? ? ? 80 BE ? 34 00 00 00"
    - 
      commands:
        offset: 1
        relative: 0
      name: "SFActionPanel::LoadHudSkin"
      signature: "50 E8 ? ? ? ? E9 ? ? ? ? E8 ? ? ? ?"
    - 
      commands: 
        offset: 5
        relative: 0
      name: "Hud::FindElement"
      signature: "68 ? ? ? ? E8 ? ? ? ? 8B 4D FC 68 ? ? ? ? 89 41 20"
    - 
      commands:
        relative: 0
      name: "SFHudOverlay::ShowSpecItemPickup"
      signature: "E8 ? ? ? ? E9 ? ? ? ? 3B 87 8C 02 00 00"
    - 
      commands: 
        offset: 1
        relative: 0
      name: "SFHudOverlay::SendRoshanPopup"
      signature: "50 E8 ? ? ? ? 5F B0 01 5E 5D"
    - 
      commands: 
        relative: 0
      name: "UnitAnnouncer::SetAnnouncerItem"
      signature: "E8 ? ? ? ? EB 32 C6 86 ? 34 00 00 01"
    - 
      commands: 
        relative: 0
      name: "DotaPlayer::PrepareUnitOrders"
      signature: "E8 ? ? ? ? 8B 43 0C 46"
    - 
      commands:
        relative: 0
      name: "EconItemView::Init"
      signature: "E8 ? ? ? ? 8D 8B 58 AA 00 00"
    - 
      commands:
        relative: 0
      name: "EconItemView::Create"
      signature: "E8 ? ? ? ? 8B F0 EB 02 33 F6 6A 00 68 0F 27 00 00 68 0F 27 00 00 FF 33"
    - 
      commands:
        relative: 0
      name: "ParticleManager::PrecacheParticleSystem"
      signature: "E8 ? ? ? ? B9 ? ? ? ? E8 ? ? ? ? 8B 55 10"
    - 
      commands:
        offset: 1
        relative: 0
      name: "ParticleManager::DestroyParticle"
      signature: "50 E8 ? ? ? ? C7 83 94 02 00 00 FF FF FF FF"
    - 
      commands:
        relative: 0
      name: "ParticleManager::CreateParticle"
      signature: "E8 ? ? ? ? 6A 00 6A 00 68 ? ? ? ? 6A 01"
    - 
      commands:
        relative: 0
      name: "ParticleManager::SetParticleControl"
      signature: "E8 ? ? ? ? F3 0F 7E 45 E0"
    - 
      commands:
        offset: 3
        relative: 0
      name: "ParticleManager::SetParticleControlEnt"
      signature: "89 42 08 E8 ? ? ? ? 8B 0D ? ? ? ? 53"
    - 
      commands:
        relative: 0
      name: "ParticleManager::ReleaseParticleIndex"
      signature: "E8 ? ? ? ? 8B 83 E8 10 00 00"
    - 
      commands:
        relative: 0
      name: "DotaPlayerResource::GetPlayerSelectedHero"
      signature: "E8 ? ? ? ? 33 C9 8B F8"
